apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default


  source:
    repoURL: https://github.com/salamsalahsalam/Argo-Prometheus.git
    targetRevision: main
    path: prometheus-configss
    helm:
      valueFiles:
        - custom-values.yaml


  destination:
    server: https://kubernetes.default.svc
    namespace: default


  syncPolicy:
    automated:
      prune: true
      selfHeal: true

