apiVersion: batch/v1
kind: Job
metadata:
  name: trigger-logicapp-webhook
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: curl
          image: curlimages/curl:latest
          command:
            - "curl"
            - "-X"
            - "POST"
            - "https://prod-09.northcentralus.logic.azure.com:443/workflows/dec24840514b4abb80d2e093b0400d4b/triggers/When_a_HTTP_request_is_received/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2FWhen_a_HTTP_request_is_received%2Frun&sv=1.0&sig=RTcVRlDKcKyZOlr19vSe6O-3oVOtM9qFNEjqxTLZztc"
            - "-d"
            - "{}"
      restartPolicy: Never
